#GitHub action to add/remove labels to issues

safe_loading:
    - '(Safe Account loading issue)'
token_balance:
    - '(Token balance not up-to-date)'
token_missing:
    - '(Token missing completely)'
tx_execution:
    - '(Transaction execution issue)'
tx_missing:
    - '(Transaction missing / not visible in app or service)'
other:
    - '(Other)'
moonbeam:
    -  '(Moonbeam)'
moonriver:
    - '(Moonriver)'
moonbase:
    - '(Moonbase)'
